artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data-ingestion
  source_url: https://github.com/soham7707/summarizer-data/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/summarizer-data.zip
  unzip_dir: artifacts/data_ingestion

  
